/* Parameters: dialog enum ID, (unused), lines per box, left offset, width */

DEFINE_DIALOG(DIALOG_SMO_KING_BOBOMB, 1, 4, 30, 200, _("\
WHAT ARE YOU\n\
DOING?\n\
TRYING TO\n\
ENTER THE\n\
ROYAL HEAD\n\
TO\n\
CONVINCE ME\n\
TO GIVE UP?\n\
HA HA!\n\
YOU ARE A\n\
FOOL IF YOU\n\
THOUGHT IT\n\
WOULD WORK!\n\
\n\
YOU FACING\n\
THE MIGHTY\n\
BOBOMB KING!\n\
YOUR TRICKS ARE\n\
USELESS\n\
AGAINST ME!\n\
\n\
I'M NOT GIVE\n\
MY\n\
POWER STAR\n\
TO A COWARD\n\
WHO CANNOT\n\
FIGHT\n\
WITH HIS\n\
BARE HANDS!"))

DEFINE_DIALOG(DIALOG_SMO_KING_WHOMP, 1, 4, 95, 200, _("\
HEY, HUMAN!\n\
WHAT ARE\n\
YOU TRYING\n\
TO DO WITH\n\
YOUR\n\
STRANGE CAP?\n\
GOING THROUGH\n\
MY MIND?\n\
I DON'T KNOW\n\
WHAT YOU ARE\n\
LOOKING FOR,\n\
BUT YOU WILL\n\
BE REALLY\n\
DISAPPOINTED!\n\
\n\
EVERYONE KNOWS\n\
THAT MY\n\
HEAD IS LIKE\n\
MY BODY:\n\
ROCK SOLID!\n\
\n\
NOTHING CAN\n\
BREAK IT!\n\
DEFINITELY\n\
NOT YOUR\n\
WEIRD CAP,\n\
YOU WIMP!\n\
\n\
...WHAT?\n\
HARD TO\n\
BELIEVE ME?\n\
FINE! I'LL\n\
SHOW YOU I'M\n\
NOT CRACKING\n\
YOU A JOKE!\n\
I'LL MAKE YOU\n\
FLATTER\n\
THAN A PANCAKE!"))
