#include "src/game/envfx_snow.h"

const GeoLayout captain_toad_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(212766),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 150, 100),
			GEO_OPEN_NODE(),
				GEO_SCALE(0, 16384),
				GEO_OPEN_NODE(),
					GEO_ASM(10, geo_update_layer_transparency),
					GEO_SWITCH_CASE(2, geo_switch_anim_state),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(1, 83, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 126, -37, 0, captain_toad_000_offset_002_mesh),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 25, 8, 0, captain_toad_002_offset_mesh),
										GEO_ANIMATED_PART(1, 34, 8, 0, captain_toad_003_offset_mesh),
										GEO_ANIMATED_PART(1, 4, 7, 38, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 37, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 9, -25, 3, captain_toad_000_offset_005_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 4, 7, -38, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 37, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 9, -25, -3, captain_toad_000_offset_008_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 61, -3, 52, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 17, 0, 4, captain_toad_000_offset_010_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(1, 61, -3, -52, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 17, 0, -4, captain_toad_000_offset_012_mesh),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, captain_toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, captain_toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, captain_toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, captain_toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, captain_toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, captain_toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, captain_toad_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, captain_toad_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
